/**
 * Tradable slices (the leg set a NAV vault actually holds) versus the disclosed book. The disclosed
 * book is never rewritten; this is read from the committed scan (`tradable-slices.json`, generated by
 * scripts/nav-vault-slices.mts) and mirrored to `insiderindex_nav_vault_slices` when that owner
 * migration (202609230001) is applied.
 */
import document from "./tradable-slices.json" with { type: "json" };

export type TradableSlice = {
  indexId: string;
  totalLegs: number;
  tradableLegs: number;
  disclosedWeightBps: number;
  eligible: boolean;
  vaultLegs: { ticker: string; mint: string; disclosedWeightBps: number; targetWeightBps: number }[];
  excluded: { ticker: string; mint: string; disclosedWeightBps: number; reason: string }[];
};

const slices = new Map((document.slices as TradableSlice[]).map(slice => [slice.indexId, slice]));

export function tradableSliceFor(indexId: string): TradableSlice | null {
  return slices.get(indexId) ?? null;
}

/** "Tradable slice: 5 of 18 holdings (72.6% of disclosed weight)". */
export function tradableSliceLabel(slice: Pick<TradableSlice, "tradableLegs" | "totalLegs" | "disclosedWeightBps">): string {
  return `Tradable slice: ${slice.tradableLegs} of ${slice.totalLegs} holdings (${(slice.disclosedWeightBps / 100).toFixed(1)}% of disclosed weight)`;
}

export const tradableSlicesMeta = { generatedAt: document.generatedAt as string, criteria: document.criteria };
