"use client";
import Link from "next/link";
import {CopyButton} from "./copy-button";
import {StockIcon} from "./social/shared";
import {Icon} from "./social/icon";
import type {HoldingStatus,PortfolioHolding} from "@/lib/disclosures/types";
import {formatDate,formatUsdRange} from "@/lib/format";
import {venueLabel} from "@/lib/venues/label";
const STATUS:Record<HoldingStatus,{label:string;hint:string}>={holding:{label:"Holding",hint:"Disclosed buys, no sells on record"},reduced:{label:"Reduced",hint:"Sold part of what they disclosed buying"},exited:{label:"Exited",hint:"Sells wiped out every disclosed buy"},sold:{label:"Sold",hint:"Only sells on record — they held it, size unknown"}};
/** Pelosi-Tracker style book: every disclosed name, venue-tagged, copy only where routable. */
export function HoldingsTable({holdings}: {holdings:PortfolioHolding[]}) {
 return <div className="holdings-table" role="table" aria-label="Disclosed holdings"><div className="holdings-head" role="row"><span role="columnheader">Name</span><span role="columnheader">Position</span><span role="columnheader">Est. value</span><span role="columnheader">Activity</span><span role="columnheader">Venue</span><span role="columnheader" className="sr-only">Action</span></div>
 {holdings.map(h=>{const status=STATUS[h.status];const copyId=h.latestBuyDisclosureId??h.latestDisclosureId;return <div key={h.ticker} className={`holdings-row status-${h.status} ${h.copyEligible?"":"not-tradable"}`} role="row"><Link role="cell" href={`/feed?q=${encodeURIComponent(h.ticker)}`} className="holding-name"><StockIcon ticker={h.ticker} size="sm"/><span><strong>{h.ticker}</strong><small>{h.issuerName!==h.ticker?h.issuerName:"\u00a0"}</small></span></Link><span role="cell" className="holding-status"><span className={`status-chip ${h.status}`} title={status.hint}>{status.label}</span></span><span role="cell" className="holding-value"><strong>{h.status==="sold"?"Unknown":h.valueLow==null&&h.valueHigh==null?"Not sized":formatUsdRange(h.valueLow,h.valueHigh)}</strong><small>{h.weightPct>0?`${(h.weightPct*100).toFixed(1)}% of book`:"—"}</small></span><span role="cell" className="holding-activity"><strong><span className="positive">{h.buys} buy{h.buys===1?"":"s"}</span> · <span className="negative">{h.sells} sell{h.sells===1?"":"s"}</span></strong><small>Last {h.lastSide==="other"?"filing":h.lastSide} {formatDate(h.lastTradeAt)}</small></span><span role="cell" className="holding-venue"><span className={`venue-chip ${h.venue}`}><Icon name={h.venue==="xstock"?"shield":h.venue==="backpack"?"up":"clock"} size={11}/>{venueLabel(h)}</span></span><span role="cell" className="holding-action"><CopyButton signalId={copyId} enabled={h.copyEligible} venue={h.venue} href={h.venueHref} label="Copy" compact/></span></div>;})}</div>;
}
