"use client";
import {useEffect,useRef,useState} from "react";
import Link from "next/link";
import {useResource} from "@/lib/frontend/use-resource";
import {PREVIEW_MODE,writeApi,errorText} from "@/lib/frontend/api";
import {usePrivySolana} from "./providers/privy-provider";
import {EquityCurve,PortfolioDonut} from "./portfolio-charts";
import {PersonAvatar} from "./person-avatar";
import {PageError,Skeleton,Breadcrumb,PartyBadge,StockIcon,EmptyState} from "./social/shared";
import {AmountField,EligibilityCheck,OrderSafety} from "./social/order-fields";
import {Icon} from "./social/icon";
import {Button} from "./ui/button";
import type {FomoProfile,PersonIndex} from "@/lib/disclosures/types";
import type {IndexAllocation,IndexPosition} from "@/lib/frontend/contracts";
import {formatDate,formatUsd} from "@/lib/format";
import {portraitFor} from "@/lib/frontend/portraits";
import {CopyButton} from "./copy-button";
import type {Disclosure} from "@/lib/disclosures/types";
import {INDEX_RULES,indexReadiness,isCountableBuy,isCrowdIndex} from "@/lib/fomo/index-readiness";
import {indexKindLabel} from "./index-card";
type QuotePayload={requestId:string;transaction:string;allocations:IndexAllocation[]};
type IndexPayload={index:PersonIndex;profile:FomoProfile|null;holding:IndexPosition|null};
export function IndexTicket({id}: {id:string}) {
 const wallet=usePrivySolana(),resource=useResource<IndexPayload>(`/api/indexes/${encodeURIComponent(id)}${wallet.solanaAddress?`?wallet=${encodeURIComponent(wallet.solanaAddress)}`:""}`),tape=useResource<{disclosures:Disclosure[]}>("/api/disclosures");
 const [amount,setAmount]=useState("1000"),[attested,setAttested]=useState(false),[quote,setQuote]=useState<QuotePayload|null>(null),[status,setStatus]=useState<string|null>(null),[busy,setBusy]=useState(false),[draft,setDraft]=useState(false),[expiry,setExpiry]=useState(0),[now,setNow]=useState(0);
 const key=`${id}:${amount}:${wallet.solanaAddress??""}`,latest=useRef(key);latest.current=key;
 useEffect(()=>{setQuote(null);setDraft(false);setAttested(false);},[id,wallet.solanaAddress]);
 useEffect(()=>{if(!quote)return;const timer=setInterval(()=>setNow(Date.now()),1000);return()=>clearInterval(timer);},[quote]);
 const valid=Number.isFinite(Number(amount))&&Number(amount)>=50,stale=Boolean(quote)&&now>=expiry,index=resource.data?.index,profile=resource.data?.profile,holding=resource.data?.holding;
 const disclosures=tape.data?.disclosures??[],readiness=index?indexReadiness(index,disclosures):null,ready=readiness?.ready??false,crowd=index?isCrowdIndex(index):false;
 const contributors=(()=>{if(!index)return [] as {id:string;name:string;latestBuy:Disclosure}[];const seen=new Map<string,{id:string;name:string;latestBuy:Disclosure}>();for(const d of [...disclosures].sort((a,b)=>Date.parse(b.filedAt)-Date.parse(a.filedAt))){if(!isCountableBuy(d))continue;if(crowd?d.kind!==index.kind:d.profileId!==index.profileId)continue;if(!seen.has(d.profileId))seen.set(d.profileId,{id:d.profileId,name:d.insiderName,latestBuy:d});}return [...seen.values()];})();
 function changeAmount(v:string){setAmount(v);setQuote(null);setDraft(false);setStatus(null);}
 async function requestQuote(){if(!index||!valid||!index.constituents.length||!ready)return;setQuote(null);setStatus(null);if(PREVIEW_MODE){setDraft(true);setStatus("Illustrative allocation only. No executable quote or transaction is created.");return;}setBusy(true);const requestKey=key;try{const data=await writeApi<QuotePayload>("/api/indexes/quote",{indexId:index.id,usdcAmount:Number(amount)});if(requestKey!==latest.current)return;if(!data.requestId||!data.transaction||!Array.isArray(data.allocations))throw new Error("Incomplete basket quote. Please retry.");setQuote(data);setNow(Date.now());setExpiry(Date.now()+60000);}catch(e){setStatus(errorText(e));}finally{setBusy(false);}}
 async function signBasket(rebalance=false){if(PREVIEW_MODE||!index||!ready||!quote||!valid||stale||Date.now()>=expiry||!attested||!wallet.authenticated||!wallet.solanaAddress)return;setBusy(true);setStatus("Waiting for your signature…");const requestKey=key;try{const signedTransaction=await wallet.signTransaction(quote.transaction);if(requestKey!==latest.current)throw new Error("Wallet or amount changed. Request a new quote.");await writeApi("/api/indexes/execute",{wallet:wallet.solanaAddress,indexId:index.id,signedTransaction,requestId:quote.requestId,usdcAmount:Number(amount),allocations:quote.allocations,rebalance});setStatus(rebalance?"Rebalance submitted. Check the updated position.":"Basket submitted. Check the updated position.");setQuote(null);resource.reload();}catch(e){setStatus(errorText(e));}finally{setBusy(false);}}
 if(resource.loading&&!index)return <Skeleton/>;if(resource.error&&!index)return <PageError error={resource.error} retry={resource.reload}/>;if(!index)return <EmptyState title="Index not found." description="This basket is unavailable."/>;
 return <div className="index-page"><Breadcrumb label={index.name}/><section className="index-page-header"><span className="index-avatar-wrap"><PersonAvatar name={index.name} imageUrl={index.imageUrl} size="xl"/><span><Icon name="grid" size={16}/></span></span><div><span className="eyebrow">{crowd?"MANY FILERS. ONE BASKET. YOUR SIGNATURE.":"ONE PERSON. ONE BASKET. YOUR SIGNATURE."}</span><h1>{index.name}<span className="accent-dot">.</span></h1><div className="inline-meta">{crowd?<span className="index-kind">{indexKindLabel(index)}</span>:<PartyBadge party={index.party} kind={index.kind}/>}<span>{index.constituents.length} xStocks</span>{readiness?<span className={`readiness-pill ${ready?"ready":"building"}`}><Icon name={ready?"check":"clock"} size={12}/>{ready?`${readiness.filers} filer${readiness.filers===1?"":"s"} · ${readiness.buys} buy${readiness.buys===1?"":"s"} · ${INDEX_RULES.windowDays}d`:"Not enough filings yet"}</span>:null}</div><p>{crowd?"Each xStock is weighted by how many filers bought it in the last "+INDEX_RULES.windowDays+" days. One quote, one signature.":"Their allowlisted buys, as one basket. Review the weights before making it yours."}</p></div></section>
 {readiness&&!ready&&!tape.loading?<div className="notice building-notice" role="status"><Icon name="clock" size={20}/><div><strong>This isn’t an index yet.</strong><p>{readiness.need} Buying is off until then — we won’t sell you a one-stock “basket”. {contributors.length?"In the meantime, follow the people below and copy a trade when they buy.":"Nothing to copy yet either."}</p></div></div>:null}
 {holding?.needsRebalance?<div className="notice rebalance-notice"><Icon name="refresh" size={20}/><div><strong>New filing. New weights.</strong><p>Your basket has a rebalance ready for review. Nothing changes until you sign.</p></div></div>:null}
 <div className="order-layout"><div className="order-information"><section className="panel"><div className="panel-heading"><h2>What’s in the basket?</h2><span className="outlined-pill">{PREVIEW_MODE?"Example weights":"Target weights"}</span></div><PortfolioDonut holdings={index.constituents.map(h=>({...h,xstockMint:h.mint,copyEligible:true}))} title={index.name}/><div className="holdings-list">{index.constituents.map(h=><div key={h.mint}><StockIcon ticker={h.ticker} size="sm"/><span><strong>{h.ticker}</strong><small>{h.xstockSymbol}</small></span><strong>{(h.weightPct*100).toFixed(1)}%</strong></div>)}</div><p className="small-text muted">{index.lastDisclosureAt?`Last disclosure: ${formatDate(index.lastDisclosureAt)}.`:"Awaiting a disclosure."} Based on the provided public-disclosure model, not a verified live portfolio.</p></section>{profile?<section className="panel"><div className="panel-heading"><h3>Historical copy path</h3><span className="muted small-text">90 days</span></div><EquityCurve points={profile.curve}/><p className="chart-disclaimer">{PREVIEW_MODE?"Synthetic chart for design review. Not actual returns.":"Historical results do not predict future returns. Disclosures can be delayed."}</p></section>:null}{contributors.length?<section className="panel"><div className="panel-heading"><h3>{crowd?"Who’s in it":"Copy one trade instead"}</h3><span className="muted small-text">{contributors.length} filer{contributors.length===1?"":"s"}</span></div><p className="small-text muted" style={{marginBottom:12}}>{crowd?"Every filer whose allowlisted buy counts toward these weights. Follow one, or copy their exact trade.":"Prefer a single trade over the basket? Copy their latest allowlisted buy."}</p><div className="filer-list compact">{contributors.slice(0,10).map(c=><div key={c.id} className="filer-row"><Link href={`/p/${encodeURIComponent(c.id)}`} className="filer-identity"><PersonAvatar name={c.name} imageUrl={portraitFor(c.id)} size="sm"/><div><strong>{c.name}</strong><span>bought <b>{c.latestBuy.xstockSymbol??c.latestBuy.ticker}</b> · {formatDate(c.latestBuy.filedAt)}</span></div></Link><div className="filer-actions"><CopyButton signalId={c.latestBuy.id} enabled label="Copy this buy"/></div></div>)}</div></section>:null}<section className="how-it-works"><span className="mini-label">A BASKET. NOT A BLACK BOX.</span><div><span>01</span><p><strong>Review the weights</strong>{crowd?"Only allowlisted xStocks, weighted by how many filers bought each one.":"Only the allowlisted xStocks in this disclosed book."}</p></div><div><span>02</span><p><strong>Quote, then sign</strong>Your allocation gets a quote. You approve the transaction.</p></div><div><span>03</span><p><strong>New filing? Your call.</strong>Review updated weights and sign each rebalance yourself.</p></div></section></div>
 <aside className="order-panel"><div className="order-panel-heading"><span className="order-icon"><Icon name="grid" size={20}/></span><div><span className="mini-label">YOUR NEXT MOVE</span><h2>{ready?"Buy the index":"Not open yet"}</h2></div></div><AmountField id="index-amount" value={amount} onChange={changeAmount} min={50} disabled={busy}/><div className="order-summary"><div><span>Basket</span><strong>{index.name}</strong></div><div><span>Assets</span><strong>{index.constituents.length} xStocks</strong></div><div><span>Execution</span><strong>User-signed</strong></div><div><span>Fees & slippage</span><strong>Review in wallet</strong></div></div><EligibilityCheck checked={attested} onChange={setAttested} disabled={busy}/>{quote||draft?<div className="basket-preview"><span className="mini-label">{draft?"ALLOCATION PREVIEW · NOT A QUOTE":"QUOTED ALLOCATION"}</span>{draft?index.constituents.map(h=><div key={h.mint}><span>{h.xstockSymbol}</span><strong>{formatUsd(Number(amount)*h.weightPct)}</strong></div>):quote?.allocations.map(h=><div key={h.mint}><span>{h.xstockSymbol} · {(h.weightPct*100).toFixed(0)}%</span><strong>{formatUsd(h.usdc)}</strong></div>)}</div>:null}{status?<p className="order-status" role="status">{status}</p>:null}{stale?<p role="alert" className="field-error">Quote expired. Refresh before signing.</p>:null}<Button className="button secondary full-width" disabled={busy||!valid||!index.constituents.length||!ready} onClick={()=>void requestQuote()}>{busy?"Working…":PREVIEW_MODE?"Preview allocation":quote?"Refresh basket quote":"Quote basket"}<Icon name="arrow" size={15}/></Button><Button className="button primary full-width" disabled={PREVIEW_MODE||busy||!ready||!quote||stale||!attested||!wallet.ready||!wallet.solanaAddress||!valid} onClick={()=>void signBasket(false)}><Icon name="shield" size={16}/>Sign & buy index</Button>{holding?<Button className="button secondary full-width" disabled={PREVIEW_MODE||busy||!quote||stale||!attested||!wallet.ready||!wallet.solanaAddress} onClick={()=>void signBasket(true)}>Sign rebalance</Button>:null}{!PREVIEW_MODE&&wallet.configured&&!wallet.ready?<p className="order-status" role="status">Wallet is connecting…</p>:null}{!PREVIEW_MODE&&wallet.ready&&!wallet.solanaAddress?<button className="text-button" onClick={()=>void wallet.connect().catch(e=>setStatus(errorText(e)))}>Connect a Solana wallet to continue</button>:null}<p className="ticket-disclaimer">{PREVIEW_MODE?"Read-only design preview. Signing and execution are disabled.":wallet.mode==="live"?"You review and sign every basket. New filings never rebalance without you.":"The included wallet is a stub until NEXT_PUBLIC_PRIVY_APP_ID is set."}</p><OrderSafety/>{crowd?<Link className="text-button center" href="/">Back to all indexes<Icon name="up" size={13}/></Link>:<Link className="text-button center" href={`/p/${encodeURIComponent(index.profileId)}`}>Back to public profile<Icon name="up" size={13}/></Link>}</aside></div></div>;
}
