"use client";
import Link from "next/link";
import {useResource} from "@/lib/frontend/use-resource";
import {useUI} from "./providers/ui-provider";
import {PageError,Skeleton,Breadcrumb,StockIcon,PartyBadge,EmptyState} from "./social/shared";
import {PersonAvatar} from "./person-avatar";
import {CopyButton} from "./copy-button";
import {Icon} from "./social/icon";
import type {Disclosure} from "@/lib/disclosures/types";
import {venueLabel} from "@/lib/venues/label";
import {formatDate,formatShares,formatUsd,formatUsdRange,shortenAddress} from "@/lib/format";
import {portraitFor} from "@/lib/frontend/portraits";
export function InspectDisclosure({id}:{id:string}){const ui=useUI(),resource=useResource<{disclosure:Disclosure}>(`/api/disclosures/${encodeURIComponent(id)}`),d=resource.data?.disclosure;
 if(resource.loading&&!d)return <Skeleton/>;if(resource.error&&!d)return <PageError error={resource.error} retry={resource.reload}/>;if(!d)return <EmptyState title="Filing unavailable." description="This record could not be found."/>;
 const lag=Math.max(0,Math.round((Date.parse(d.filedAt)-Date.parse(d.transactionDate))/86400000)),mock=d.source.startsWith("mock"),buy=d.side==="buy",sell=d.side==="sell";
 const rows:[string,string][]=[["Reported transaction",`${d.transactionCode} · ${d.side}`],["Transaction date",formatDate(d.transactionDate)],["Filed",formatDate(d.filedAt)],["Reported amount",formatUsdRange(d.amountLow,d.amountHigh)],["Shares",formatShares(d.sharesAmount)],["Price per share",formatUsd(d.pricePerShare)],["Transaction value",formatUsd(d.transactionValue)],["Shares owned after",formatShares(d.sharesOwnedAfter)],["10b5-1 plan",d.is10b51?"Yes":"No"],["Source",d.source],["Venue",venueLabel(d)],["Venue symbol",d.venueSymbol??"—"],["Solana mint",d.mint?shortenAddress(d.mint,8):"—"]];
 return <div className="disclosure-page"><Breadcrumb label="Inspect a filing"/><div className="page-intro"><div><span className="eyebrow">LESS SPECULATION. MORE RECEIPTS.</span><h1>Read the fine print<span className="accent-dot">.</span></h1><p>A public record, not a real-time trade alert.</p></div><span className="outlined-pill"><Icon name="file" size={14}/>{mock?"Synthetic example":d.kind==="politician"?"Congress PTR":"SEC Form 4"}</span></div><div className="inspect-layout"><section className="panel filing-document"><div className="filing-document-top"><Link href={`/p/${encodeURIComponent(d.profileId)}`} className="signal-person"><PersonAvatar name={d.insiderName} imageUrl={portraitFor(d.profileId)}/><div><strong>{d.insiderName}</strong><PartyBadge party={d.party} kind={d.kind}/></div></Link><span className={`side-label ${buy?"buy":sell?"sell":""}`}>{d.side.toUpperCase()}</span></div><div className="filing-asset"><StockIcon ticker={d.ticker} size="lg"/><div><h2>{d.issuerName}</h2><p>{d.ticker} · {venueLabel(d)}</p></div></div>{mock?<div className="notice">This is a fictional design fixture, not an actual trade by {d.insiderName}.</div>:null}<dl className="filing-rows">{rows.map(([label,value])=><div key={label}><dt>{label}</dt><dd>{value}</dd></div>)}</dl><div className="accession-box"><span className="mini-label">SOURCE RECORD IDENTIFIER</span><code>{d.accessionNumber}</code><button className="icon-button" aria-label="Copy filing identifier" onClick={()=>void navigator.clipboard.writeText(d.accessionNumber).then(()=>ui.toast("Record identifier copied.")).catch(()=>ui.toast("Select and copy the identifier shown here."))}><Icon name="copy" size={16}/></button></div></section><aside><section className="panel filing-timeline"><h3>A little context goes a long way.</h3><div><i/><p><small>THE ORIGINAL TRADE</small><strong>{formatDate(d.transactionDate)}</strong><span>The transaction date in the record.</span></p></div><div><i/><p><small>THE DISCLOSURE</small><strong>{formatDate(d.filedAt)}</strong><span>{Number.isFinite(lag)?`${lag} days after the reported trade.`:"Reporting delay is unavailable."}</span></p></div><div><i/><p><small>YOUR DECISION</small><strong>Now, not then.</strong><span>You trade at a new quote, not their original price.</span></p></div></section><section className="panel filing-action"><h3>Receipt read. Your move?</h3><p>Copy just this one trade at today’s price, or open the profile to follow them and see whether their buys add up to an index.</p><CopyButton signalId={d.id} enabled={d.tradeEligible&&d.side!=="other"} venue={d.venue}/><Link className="button secondary full-width" href={`/p/${encodeURIComponent(d.profileId)}`}>Follow {d.insiderName.split(" ").at(-1)}<Icon name="arrow" size={15}/></Link><div className="order-safety"><Icon name="shield" size={16}/><span>You review and sign every order.</span></div></section></aside></div></div>;
}
