"use client";
import { useEffect, useState } from "react";
import Link from "next/link";
import { getOperation, prepareNext, type ObservedOperation } from "@/lib/frontend/vault-api";
import { usePrivySolana } from "./providers/privy-provider";
import { WalletButton } from "./wallet-button";
import { Icon } from "./social/icon";
import { errorText, PREVIEW_MODE } from "@/lib/frontend/api";
import styles from "./operation-status.module.css";
function label(x:string){return x.toLowerCase().replaceAll("_"," ").replace(/^./,m=>m.toUpperCase())}
export function OperationStatus({operationId}:{operationId:string}){const wallet=usePrivySolana();const[op,setOp]=useState<ObservedOperation|null>(null);const[error,setError]=useState<string|null>(null);const[busy,setBusy]=useState(false);async function load(){setBusy(true);setError(null);try{setOp(await getOperation(operationId))}catch(e){setError(errorText(e))}finally{setBusy(false)}}useEffect(()=>{void load()},[operationId]);async function next(){if(!wallet.solanaAddress||!op)return;setBusy(true);try{await prepareNext(op.operationId,wallet.solanaAddress);await load()}catch(e){setError(errorText(e));setBusy(false)}}return <div className={styles.page}><Link href="/positions" className={styles.back}><Icon name="arrow" size={13} style={{transform:"rotate(180deg)"}}/>Your portfolio</Link><header><span>RESUMABLE OPERATION</span><h1>{op?label(op.phase):"Loading operation…"}</h1><p>Closing InsiderIndex does not erase native vault state. This page reconciles confirmed receipts and tells you the next safe action.</p></header>{PREVIEW_MODE?<div className={styles.demo}>Design-flow fixture · production status must come from chain-verified backend evidence.</div>:null}{error?<div className={styles.error}>{error}</div>:op?<div className={styles.grid}><section><small>OPERATION</small><code>{op.operationId}</code><div><span>Kind</span><b>{op.kind}</b></div><div><span>Current phase</span><b>{label(op.phase)}</b></div><div><span>Complete</span><b>{op.complete?"Yes":"No"}</b></div><div><span>Next action</span><b>{op.nextAction??"Reconcile state"}</b></div></section><section><small>CHAIN OBLIGATIONS</small><div><span>Outstanding claims</span><b>{op.outstandingClaims?.length??0}</b></div><div><span>Confirmed credits</span><b>{op.credits?.length??0}</b></div><div><span>Blockers</span><b>{op.blockers?.length??0}</b></div>{op.blockers?.map((x,i)=><p key={i}>{x}</p>)}</section></div>:null}<div className={styles.actions}>{!wallet.authenticated?<WalletButton/>:<button disabled={busy} onClick={()=>void next()}>{busy?"Checking…":"Continue safely"}</button>}<button disabled={busy} onClick={()=>void load()}>Refresh</button></div></div>}
