"use client";
import {useId,useState} from "react";
import type {BacktestPoint,PortfolioHolding} from "@/lib/disclosures/types";
import {formatPct,formatUsd} from "@/lib/format";
export const CHART_COLORS=["#93bb36","#8980eb","#66abd8","#e89f65","#cd7394","#5caaa0"];
export function Sparkline({points,negative=false}: {points:BacktestPoint[];negative?:boolean}) {const valid=points.filter(p=>Number.isFinite(p.equity));if(valid.length<2)return <span className="muted">—</span>;const min=Math.min(...valid.map(p=>p.equity)),max=Math.max(...valid.map(p=>p.equity)),span=max-min||1;return <svg viewBox="0 0 100 34" className={`sparkline ${negative?"negative":""}`} role="img" aria-label="Historical example curve"><polyline points={valid.map((p,i)=>`${i/(valid.length-1)*100},${30-(p.equity-min)/span*26}`).join(" ")} fill="none" stroke="currentColor" strokeWidth="2" strokeLinejoin="round" strokeLinecap="round"/></svg>;}
export function PortfolioDonut({holdings,title="Index",unit="names"}: {holdings:Pick<PortfolioHolding,"ticker"|"weightPct"|"venueSymbol"|"valueUsd">[];title?:string;unit?:string}) {
 const valid=holdings.filter(h=>Number.isFinite(h.weightPct)&&h.weightPct>0),total=valid.reduce((s,h)=>s+h.weightPct,0);let offset=0;
 if(!valid.length)return <p className="empty-chart">No allocation data yet.</p>;
 return <div className="portfolio-donut"><svg viewBox="0 0 160 160" role="img" aria-label={`${title} allocation: ${valid.map(h=>`${h.ticker} ${(h.weightPct*100).toFixed(1)} percent`).join(", ")}`}><circle cx="80" cy="80" r="61" fill="none" stroke="var(--surface-alt)" strokeWidth="18"/>{valid.map((h,i)=>{const fraction=h.weightPct/total,start=offset;offset+=fraction;return <circle key={`${h.ticker}-${i}`} cx="80" cy="80" r="61" fill="none" stroke={CHART_COLORS[i%CHART_COLORS.length]} strokeWidth="18" pathLength="100" strokeDasharray={`${fraction*100} ${100-fraction*100}`} strokeDashoffset={-start*100} transform="rotate(-90 80 80)"/>;})}<text x="80" y="78" textAnchor="middle" className="donut-number">{valid.length}</text><text x="80" y="96" textAnchor="middle" className="donut-label">{unit}</text></svg><div className="donut-legend">{valid.map((h,i)=><div key={`${h.ticker}-${i}`}><span><i style={{background:CHART_COLORS[i%CHART_COLORS.length]}}/>{h.venueSymbol??h.ticker}</span><strong>{(h.weightPct*100).toFixed(1)}%</strong></div>)}</div></div>;
}
export function EquityCurve({points,label="90d historical copy path"}: {points:BacktestPoint[];label?:string}) {
 const id=useId().replaceAll(":",""),[hover,setHover]=useState<number|null>(null),valid=points.filter(p=>Number.isFinite(p.equity));
 if(valid.length<2)return <p className="empty-chart">No return series yet. We chart performance only when it can be computed from dated trades and real prices — nothing is drawn until then.</p>;
 const width=620,height=180,min=Math.min(...valid.map(p=>p.equity)),max=Math.max(...valid.map(p=>p.equity)),span=max-min||1;
 const coords=valid.map((p,i)=>({x:i/(valid.length-1)*width,y:height-16-(p.equity-min)/span*(height-32)}));
 const change=valid[0].equity?(valid.at(-1)!.equity-valid[0].equity)/Math.abs(valid[0].equity):0;
 const line=coords.map(c=>`${c.x},${c.y}`).join(" "),selected=hover===null?null:Math.min(hover,valid.length-1),color=change>=0?"var(--positive)":"var(--negative)";
 return <div className="equity-curve"><div className="chart-topline"><span>{label}</span><strong style={{color}}>{selected===null?formatPct(change):`${valid[selected].label} · ${formatUsd(valid[selected].equity)}`}</strong></div><svg viewBox={`0 0 ${width} ${height}`} role="img" aria-label={`${label}: ${formatPct(change)}. Use arrow keys to explore data.`} tabIndex={0} onKeyDown={e=>{if(e.key==="ArrowRight"||e.key==="ArrowLeft"){e.preventDefault();setHover(Math.max(0,Math.min(valid.length-1,(hover??0)+(e.key==="ArrowRight"?1:-1))));}}} onMouseLeave={()=>setHover(null)} onMouseMove={e=>{const r=e.currentTarget.getBoundingClientRect();setHover(Math.round(Math.max(0,Math.min(1,(e.clientX-r.left)/r.width))*(valid.length-1)));}}><defs><linearGradient id={`fill-${id}`} x1="0" x2="0" y1="0" y2="1"><stop offset="0%" stopColor={color} stopOpacity=".2"/><stop offset="100%" stopColor={color} stopOpacity="0"/></linearGradient></defs>{[30,90,150].map(y=><line key={y} x1="0" x2={width} y1={y} y2={y} stroke="var(--border)" strokeDasharray="3 6"/>)}<polygon points={`0,${height} ${line} ${width},${height}`} fill={`url(#fill-${id})`}/><polyline fill="none" stroke={color} strokeWidth="3" strokeLinejoin="round" strokeLinecap="round" points={line}/>{selected!==null?<g><line x1={coords[selected].x} x2={coords[selected].x} y1="0" y2={height} stroke="var(--muted-foreground)" strokeDasharray="4 4"/><circle cx={coords[selected].x} cy={coords[selected].y} r="5" fill={color} stroke="var(--card)" strokeWidth="3"/></g>:null}</svg><div className="chart-labels"><span>{valid[0].label}</span><span>{valid[Math.floor(valid.length/2)].label}</span><span>{valid.at(-1)!.label}</span></div></div>;
}
