"use client";
import {useState} from "react";
import Link from "next/link";
import {useResource} from "@/lib/frontend/use-resource";
import {PREVIEW_MODE,writeApi,errorText} from "@/lib/frontend/api";
import {usePrivySolana} from "./providers/privy-provider";
import {useUI} from "./providers/ui-provider";
import {PersonAvatar} from "./person-avatar";
import {CopyButton} from "./copy-button";
import {SignalCard} from "./signal-card";
import {EquityCurve,PortfolioDonut} from "./portfolio-charts";
import {PageError,Skeleton,PartyBadge,Breadcrumb,EmptyState} from "./social/shared";
import {Icon} from "./social/icon";
import type {FomoProfile,CopySignal,HorizonKey} from "@/lib/disclosures/types";
import type {Follow} from "@/lib/frontend/contracts";
import {formatPct,formatUsd} from "@/lib/format";
export function ProfileView({id}: {id:string}) {
 const wallet=usePrivySolana(),ui=useUI(),resource=useResource<{profile:FomoProfile;trades:CopySignal[]}>(`/api/profiles/${encodeURIComponent(id)}`),followsRes=useResource<{follows:Follow[]}>(wallet.solanaAddress?`/api/follows?wallet=${encodeURIComponent(wallet.solanaAddress)}`:null);
 const [busy,setBusy]=useState(false),[horizon,setHorizon]=useState<HorizonKey>("90d"),[tab,setTab]=useState("activity"),[followError,setFollowError]=useState<string|null>(null);
 const profile=resource.data?.profile,trades=resource.data?.trades??[],follow=followsRes.data?.follows.find(f=>f.profileId===id),isFollowing=PREVIEW_MODE?ui.previewFollows.includes(id):Boolean(follow);
 async function setFollowState(next:{unfollow?:boolean;autoCopy?:boolean}) {
  if(PREVIEW_MODE){ui.togglePreviewFollow(id);ui.toast(isFollowing?"Removed from your preview circle.":"Added to your preview circle. Saved on this device.");return;}
  if(!wallet.solanaAddress){try{await wallet.connect();ui.toast("Wallet ready. Tap Follow to save this profile.");}catch{ui.toast("Wallet connection failed.");}return;}
  setBusy(true);setFollowError(null);
  try{await writeApi("/api/follows",{wallet:wallet.solanaAddress,profileId:id,autoCopy:next.autoCopy??follow?.autoCopy??false,unfollow:next.unfollow??false});followsRes.reload();ui.toast(next.unfollow?"Unfollowed.":next.autoCopy?"New copies will queue for your review. Nothing auto-executes.":"Your circle just got more interesting.");}catch(e){setFollowError(errorText(e));}finally{setBusy(false);}
 }
 async function share(){try{await navigator.clipboard.writeText(location.href);ui.toast("Profile link copied.");}catch{ui.toast("Copy this profile’s URL from the address bar.");}}
 if(resource.loading&&!profile)return <Skeleton/>;if(resource.error&&!profile)return <PageError error={resource.error} retry={resource.reload}/>;if(!profile)return <EmptyState title="Profile not found." description="This public profile is unavailable."/>;
 const insight=profile.insights.find(i=>i.horizon===horizon);
 return <div className="profile-page"><Breadcrumb label="Public profile"/><section className="profile-hero"><div className={`profile-cover ${profile.party==="Republican"?"cover-red":profile.party===null?"cover-violet":""}`}><span className="cover-word">FOLLOW THE FILINGS.</span><span className="cover-star">✳</span><span className="cover-label"><Icon name="file" size={13}/>{PREVIEW_MODE?"ILLUSTRATIVE PROFILE":"PUBLIC DISCLOSURE PROFILE"}</span></div><div className="profile-identity"><PersonAvatar name={profile.name} imageUrl={profile.imageUrl} size="xl"/><div className="profile-identity-main"><div className="profile-title-row"><h1>{profile.name}</h1><PartyBadge party={profile.party} kind={profile.kind}/></div><p>{profile.handle}<span>·</span>{profile.title}</p><span className="follow-count"><Icon name="people" size={14}/>{profile.followers.toLocaleString()} followers{PREVIEW_MODE?" · example count":""}</span></div><button className="icon-button" aria-label="Share profile" onClick={()=>void share()}><Icon name="share" size={19}/></button></div><div className="profile-bottom"><p>Watch the paper trail. Make the decision yours.</p><div className="profile-buttons"><button className={`button ${isFollowing?"secondary":"ink-theme"}`} disabled={busy} onClick={()=>void setFollowState({unfollow:isFollowing})}><Icon name={isFollowing?"check":"people"} size={15}/>{busy?"Saving…":isFollowing?"Following":!wallet.solanaAddress&&!PREVIEW_MODE?"Connect to follow":"Follow"}</button><CopyButton signalId={profile.latestEligibleSignalId} enabled={Boolean(profile.latestEligibleSignalId)} label="Copy latest print"/><Link className="button secondary" href={`/indexes/${encodeURIComponent(profile.index.id)}`}><Icon name="grid" size={15}/>Buy index</Link></div></div></section>
 {followError||followsRes.error?<div className="notice error" role="alert">{followError??followsRes.error}</div>:null}
 {follow&&!PREVIEW_MODE?<div className="queue-setting"><div><Icon name="bell" size={16}/><span>Queue their next eligible print <small>Review and sign, never autopilot.</small></span></div><button className={`toggle ${follow.autoCopy?"on":""}`} role="switch" aria-checked={follow.autoCopy} aria-label="Queue next copy for review" disabled={busy} onClick={()=>void setFollowState({autoCopy:!follow.autoCopy})}><span/></button></div>:null}
 <section className="profile-performance"><div className="section-heading"><h2>The numbers, not the narrative.</h2><div className="segmented-control" aria-label="Performance horizon">{(["24h","30d","90d"] as HorizonKey[]).map(h=><button key={h} className={horizon===h?"selected":""} aria-pressed={horizon===h} onClick={()=>setHorizon(h)}>{h}</button>)}</div></div><div className="stat-grid"><div className="stat-card"><span>{PREVIEW_MODE?"Illustrative":"Historical"} return · {horizon}</span><strong className={(insight?.returnPct??0)>=0?"positive":"negative"}>{formatPct(insight?.returnPct)}</strong><small>Not a forecast</small></div><div className="stat-card"><span>Tracked disclosures</span><strong>{insight?.trades??"—"}</strong><small>Over selected period</small></div><div className="stat-card"><span>Disclosed volume</span><strong>{formatUsd(insight?.volumeUsd)}</strong><small>Reported, not live volume</small></div><div className="stat-card"><span>Historical hit rate</span><strong>{insight?.hitRate!=null?`${(insight.hitRate*100).toFixed(0)}%`:"—"}</strong><small>Methodology from source API</small></div></div></section>
 <div className="profile-content-grid"><div><section className="panel chart-panel"><div className="panel-heading"><h3>The copy path</h3><span className="outlined-pill">{PREVIEW_MODE?"Synthetic example":"Historical"}</span></div><EquityCurve points={profile.curve} label="90d curve · rebased portfolio value"/><p className="chart-disclaimer">The curve remains the supplied 90d series. Horizon buttons change the stats above, not the underlying chart. Historical performance is not a promise.</p></section><div className="section-heading activity-heading"><div className="text-tabs" role="group" aria-label="Profile content"><button aria-pressed={tab==="activity"} className={tab==="activity"?"selected":""} onClick={()=>setTab("activity")}>The paper trail <span>{trades.length}</span></button><button aria-pressed={tab==="book"} className={tab==="book"?"selected":""} onClick={()=>setTab("book")}>Disclosed book</button></div></div>{tab==="activity"?<div className="signal-list">{trades.length?trades.map(t=><SignalCard key={t.id} signal={t}/>):<EmptyState title="No prints yet." description="Public disclosures will appear here when available."/>}</div>:<section className="panel"><h3>Disclosed holdings</h3><PortfolioDonut holdings={profile.portfolio} title="Disclosed book"/><p className="muted small-text">Estimated from supplied disclosures, not a verified brokerage balance. Index eligibility can differ from the full disclosed book.</p></section>}</div><aside><section className="panel profile-index-panel"><span className="mini-label">THE WHOLE BOOK, REMIXED.</span><h3>{profile.index.name}</h3><PortfolioDonut holdings={profile.index.constituents.map(h=>({...h,xstockMint:h.mint,copyEligible:true}))} title="Eligible basket"/><p>The allowlisted part of this book, in one user-signed basket.</p><Link href={`/indexes/${encodeURIComponent(profile.index.id)}`} className="button primary full-width">Explore the index<Icon name="arrow" size={16}/></Link><span className="index-card-caption"><Icon name="shield" size={13}/>You approve every rebalance</span></section><div className="rail-fineprint"><Icon name="info" size={16}/><p>{PREVIEW_MODE?"Fictional figures for UI review. This page makes no claim about actual trading or returns.":"Tracking does not imply affiliation, endorsement, or that the named person placed every household transaction."}</p></div></aside></div></div>;
}
