"use client";
import {useEffect,useRef} from "react";
import Link from "next/link";
import {usePathname,useRouter} from "next/navigation";
import {useUI,type Lane,type Theme} from "@/components/providers/ui-provider";
import {WalletButton} from "@/components/wallet-button";
import {Icon,BrandMark} from "@/components/social/icon";
const nav: {label:string;short:string;icon:string;view:Lane|null;href:string}[]=[{label:"Indexes",short:"Indexes",icon:"grid",view:null,href:"/"},{label:"Feed",short:"Feed",icon:"bolt",view:"live",href:"/feed"},{label:"Following",short:"Following",icon:"people",view:"following",href:"/feed?view=following"},{label:"My positions",short:"Positions",icon:"wallet",view:null,href:"/positions"}];
function crumb(path:string){return path==="/"?"Indexes":path==="/feed"?"Feed":path.startsWith("/p/")?"Public profile":path.startsWith("/indexes/")?"Index":path.startsWith("/positions")?"My positions":path.startsWith("/trade/")?"Copy one trade":"Filing";}
export function SiteHeader(){const ui=useUI(),path=usePathname(),router=useRouter(),input=useRef<HTMLInputElement>(null);
 useEffect(()=>{const onKey=(e:KeyboardEvent)=>{const target=e.target as HTMLElement;if(e.key==="/"&&!/input|textarea|select/i.test(target.tagName)&&!target.isContentEditable){e.preventDefault();input.current?.focus();}if(e.key==="Escape")input.current?.blur();};document.addEventListener("keydown",onKey);return()=>document.removeEventListener("keydown",onKey);},[]);
 const active=(n:typeof nav[number])=>n.href==="/"?path==="/":n.href==="/positions"?path.startsWith("/positions"):path==="/feed"&&ui.lane===n.view;
 const goFeed=()=>{if(path!=="/feed")router.push(ui.query?`/feed?q=${encodeURIComponent(ui.query)}`:"/feed");};
 return <><aside className="sidebar"><Link href="/" className="brand"><BrandMark/><span>stocklana<span className="brand-dot">.</span></span></Link><div className="sidebar-heading">PUBLIC FILINGS. YOUR BASKETS.</div><nav className="desktop-nav" aria-label="Primary navigation">{nav.map(n=><Link key={n.label} href={n.href} onClick={()=>{if(n.view)ui.setLane(n.view);ui.setQuery("");}} className={`nav-item ${active(n)?"active":""}`} aria-current={active(n)?"page":undefined}><Icon name={n.icon}/>{n.label}{n.href==="/"?<span className="nav-dot"/>:null}</Link>)}</nav><div className="sidebar-bottom"><div className="sidebar-sticker"><Icon name="landmark" size={28}/><p>Enough of them buying?<br/><strong>That’s an index.</strong></p><span>Just one? Follow and copy the trade.</span></div><div className="theme-switch" role="group" aria-label="Color theme">{([['light','sun'],['dark','moon'],['system','monitor']] as [Theme,string][]).map(([t,i])=><button key={t} onClick={()=>ui.setTheme(t)} aria-pressed={ui.theme===t} aria-label={`Use ${t} theme`} className={ui.theme===t?"selected":""}><Icon name={i} size={16}/><span>{t}</span></button>)}</div><div className="sidebar-foot"><span className="solana-bars">≋</span> Built for Solana<span>v0.3</span></div></div></aside>
 <header className="site-header"><div className="header-left"><Link href="/" className="brand mobile-brand"><BrandMark/><span>stocklana.</span></Link><span className="header-breadcrumb">{crumb(path)}</span><span className="network-pill"><i/>Solana</span></div><form className="header-search" role="search" onSubmit={e=>{e.preventDefault();goFeed();}}><Icon name="search" size={17}/><input ref={input} value={ui.query} onChange={e=>ui.setQuery(e.target.value)} placeholder="Search the feed: people, tickers…" aria-label="Search people and tickers in the feed"/><kbd>/</kbd></form><div className="header-actions"><button className="icon-button theme-quick" aria-label={ui.theme==="dark"?"Switch to light mode":"Switch to dark mode"} onClick={()=>ui.setTheme(document.documentElement.classList.contains("dark")?"light":"dark")}><Icon name={ui.theme==="dark"?"sun":"moon"}/></button><WalletButton/></div></header>
 <nav className="mobile-nav" aria-label="Mobile navigation">{nav.map(n=><Link key={n.label} href={n.href} onClick={()=>{if(n.view)ui.setLane(n.view);ui.setQuery("");}} className={active(n)?"active":""} aria-current={active(n)?"page":undefined}><Icon name={n.icon} size={21}/><span>{n.short}</span></Link>)}</nav></>;
}
