const PORTRAITS: Record<string, string> = {
  "insider-0001199036": "/portraits/jensen-huang.jpg",
  "jensen-huang": "/portraits/jensen-huang.jpg",
  "insider-0001214156": "/portraits/tim-cook.jpg",
  "tim-cook": "/portraits/tim-cook.jpg",
  "insider-0001494730": "/portraits/kimbal-musk.jpg",
  "kimbal-musk": "/portraits/kimbal-musk.jpg",
  "insider-0001623824": "/portraits/satya-nadella.jpg",
  "satya-nadella": "/portraits/satya-nadella.jpg",
  "insider-0001548760": "/portraits/mark-zuckerberg.jpg",
  "mark-zuckerberg": "/portraits/mark-zuckerberg.jpg",
  "insider-0001537655": "/portraits/andy-jassy.jpg",
  "andy-jassy": "/portraits/andy-jassy.jpg",
  "insider-0001635575": "/portraits/sundar-pichai.jpg",
  "sundar-pichai": "/portraits/sundar-pichai.jpg",
  "insider-0001533756": "/portraits/ted-sarandos.jpg",
  "ted-sarandos": "/portraits/ted-sarandos.jpg",
  "insider-0001463207": "/portraits/brian-armstrong.jpg",
  "brian-armstrong": "/portraits/brian-armstrong.jpg",
  "insider-0001037443": "/portraits/michael-saylor.png",
  "michael-saylor": "/portraits/michael-saylor.png",
  "P000197": "/portraits/nancy-pelosi.jpg",
  "pol-nancy-pelosi": "/portraits/nancy-pelosi.jpg",
  "idx-nancy-pelosi": "/portraits/nancy-pelosi.jpg",
  "nancy-pelosi": "/portraits/nancy-pelosi.jpg",
  "pol-ro-khanna": "/portraits/ro-khanna.jpg",
  "ro-khanna": "/portraits/ro-khanna.jpg",
  "pol-josh-gottheimer": "/portraits/josh-gottheimer.jpg",
  "josh-gottheimer": "/portraits/josh-gottheimer.jpg",
  "pol-debbie-wasserman-schultz": "/portraits/debbie-wasserman-schultz.jpg",
  "debbie-wasserman-schultz": "/portraits/debbie-wasserman-schultz.jpg",
  "pol-marjorie-taylor-greene": "/portraits/marjorie-taylor-greene.jpg",
  "marjorie-taylor-greene": "/portraits/marjorie-taylor-greene.jpg",
  "pol-dan-crenshaw": "/portraits/dan-crenshaw.jpg",
  "dan-crenshaw": "/portraits/dan-crenshaw.jpg",
  "pol-michael-mccaul": "/portraits/michael-mccaul.jpg",
  "michael-mccaul": "/portraits/michael-mccaul.jpg",
  "pol-austin-scott": "/portraits/austin-scott.jpg",
  "austin-scott": "/portraits/austin-scott.jpg",
  "S001217": "/portraits/rick-scott.jpg",
  "rick-scott": "/portraits/rick-scott.jpg",
  "pol-rick-scott": "/portraits/rick-scott.jpg",
  "F000110": "/portraits/cleo-fields.jpg",
  "cleo-fields": "/portraits/cleo-fields.jpg",
  "pol-cleo-fields": "/portraits/cleo-fields.jpg",
  "G000583": "/portraits/josh-gottheimer.jpg",
  "H001082": "/portraits/kevin-hern.jpg",
  "kevin-hern": "/portraits/kevin-hern.jpg",
  "pol-kevin-hern": "/portraits/kevin-hern.jpg",
  "C001123": "/portraits/gilbert-ray-cisneros.jpg",
  "gilbert-ray-cisneros": "/portraits/gilbert-ray-cisneros.jpg",
  "pol-gilbert-ray-cisneros": "/portraits/gilbert-ray-cisneros.jpg",
  "S001229": "/portraits/jefferson-shreve.jpg",
  "jefferson-shreve": "/portraits/jefferson-shreve.jpg",
  "pol-jefferson-shreve": "/portraits/jefferson-shreve.jpg",
  "G000596": "/portraits/marjorie-taylor-greene.jpg",
  "B001260": "/portraits/vern-buchanan.jpg",
  "vern-buchanan": "/portraits/vern-buchanan.jpg",
  "pol-vern-buchanan": "/portraits/vern-buchanan.jpg",
  "K000383": "/portraits/angus-s-jr-king.jpg",
  "angus-s-jr-king": "/portraits/angus-s-jr-king.jpg",
  "pol-angus-s-jr-king": "/portraits/angus-s-jr-king.jpg",
  "F000246": "/portraits/patrick-fallon.jpg",
  "patrick-fallon": "/portraits/patrick-fallon.jpg",
  "pol-patrick-fallon": "/portraits/patrick-fallon.jpg",
  "L000590": "/portraits/susie-lee.jpg",
  "susie-lee": "/portraits/susie-lee.jpg",
  "pol-susie-lee": "/portraits/susie-lee.jpg",
  "M001236": "/portraits/tim-moore.jpg",
  "tim-moore": "/portraits/tim-moore.jpg",
  "pol-tim-moore": "/portraits/tim-moore.jpg",
  "M001136": "/portraits/lisa-mcclain.jpg",
  "lisa-mcclain": "/portraits/lisa-mcclain.jpg",
  "pol-lisa-mcclain": "/portraits/lisa-mcclain.jpg",
  "C001047": "/portraits/shelley-moore-capito.jpg",
  "shelley-moore-capito": "/portraits/shelley-moore-capito.jpg",
  "pol-shelley-moore-capito": "/portraits/shelley-moore-capito.jpg",
  "T000488": "/portraits/shri-thanedar.jpg",
  "shri-thanedar": "/portraits/shri-thanedar.jpg",
  "pol-shri-thanedar": "/portraits/shri-thanedar.jpg",
  "S001198": "/portraits/dan-sullivan.jpg",
  "dan-sullivan": "/portraits/dan-sullivan.jpg",
  "pol-dan-sullivan": "/portraits/dan-sullivan.jpg",
  "L000595": "/portraits/julia-letlow.jpg",
  "julia-letlow": "/portraits/julia-letlow.jpg",
  "pol-julia-letlow": "/portraits/julia-letlow.jpg",
  "G000603": "/portraits/brandon-gill.jpg",
  "brandon-gill": "/portraits/brandon-gill.jpg",
  "pol-brandon-gill": "/portraits/brandon-gill.jpg",
  "B001305": "/portraits/ted-budd.jpg",
  "ted-budd": "/portraits/ted-budd.jpg",
  "pol-ted-budd": "/portraits/ted-budd.jpg",
};


export function portraitFor(profileId: string): string | null {
  return PORTRAITS[profileId] ?? null;
}

export function initialsFor(name: string): string {
  return name
    .split(/\s+/)
    .filter(Boolean)
    .slice(0, 2)
    .map((part) => part[0]?.toUpperCase() ?? "")
    .join("");
}
